### ISSUE TITLE
[Exercise 5: filtered LS] verification

### ISSUE THREAD

**Issue by nixrod** [rvagg/learnyounode#245] opened 2015-02-25 09:26 UTC
In the verification of a passed Exercise 5 the program tells the user:
>V Used synchronous method fs.readdir()

fs.readdir() is asynchronous.
http://nodejs.org/api/fs.html#fs_fs_readdir_path_callback

**Comment by martinheidegger** [comment] 2015-02-25 09:27
Duplicate of this I think: https://github.com/rvagg/learnyounode/pull/242

**Comment by nixrod** [comment] 2015-02-25 09:29
Yes it is, thanks and sorry :)

**Closed** 2015-02-25 09:30 UTC
