### ISSUE TITLE
Install folder madness

### ISSUE THREAD

**Issue by cavpollo** [rvagg/learnyounode#158] opened 2014-12-14 01:28 UTC
I tried installing the tutorial with npm, but things just went bad and I dont know where to start to fix it.

	cavpollo@cavpollo-Inspiron-N5110:~/ccs/tutorial1$ sudo npm install learnyounode -g
	/home/cavpollo/ccs/tutorial1/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /usr/bin/learnyounode -> /home/cavpollo/ccs/tutorial1/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /usr/lib/node_modules/learnyounode/learnyounode.js
	learnyounode@1.0.6 /home/cavpollo/ccs/tutorial1/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /home/cavpollo/Downloads/Titanium_Studio/[sudo] password for cavpollo: /usr/lib/node_modules/learnyounode
	├── workshopper-boilerplate@0.0.1
	├── duplexer@0.1.1
	├── after@0.8.1
	├── rimraf@2.2.8
	├── through@2.3.6
	├── boganipsum@0.1.0
	├── hyperquest@0.2.0 (through@2.2.7)
	├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
	├── colors-tmpl@0.1.1 (colors@0.6.2)
	├── concat-stream@1.4.7 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
	├── through2@0.4.2 (readable-stream@1.0.33, xtend@2.1.2)
	├── workshopper-wrappedexec@0.1.2 (xtend@2.1.2)
	├── through2-map@1.4.0 (xtend@3.0.0, terminus@1.0.11, through2@0.5.1)
	├── workshopper-exercise@0.2.3 (tuple-stream@0.0.2, split@0.3.2, xtend@2.1.2)
	├── stream-browserify@1.0.0 (inherits@2.0.1, readable-stream@1.0.33)
	├── bl@0.7.0 (readable-stream@1.0.33)
	└── workshopper@1.3.3 (map-async@0.1.1, xtend@3.0.0, mkdirp@0.3.5, visualwidth@0.0.1, optimist@0.6.1, terminal-menu@0.3.2, msee@0.1.1)

As you can see, I called the command "sudo npm install learnyounode -g" from the tutorial folder, and for some reason it messed up the filepath making it huge. Ive repeated the process, and everytime I get the same result. All I know is that the TitaniumStudio path may be interfering some way... =(

**Comment by EverlessDrop41** [comment] 2015-01-15 20:18
I've got a very similar issue to this

**Comment by cavpollo** [comment] 2015-01-15 20:30
@EverlessDrop41 I think I managed to fix my issue. If I remember correctly, by going to the etc folder and while looking for a npm configuration file, I stumbled upon a file that had the exact path that was interfering with the installation. All I did was removing the extra filepath annoying text and things got back to normal. If I ever find the name of the file or path, I'll remember to post it around here.

**Comment by EverlessDrop41** [comment] 2015-01-15 20:38
Hmm, not sure if I have the same problem. I run the same command as you (`sudo npm install -g learnyounode`) and then it installs a load of file but then I end up with this: 
```
 npm http 304 https://registry.npmjs.org/abbrev
 /usr/local/bin/learnyounode -> /usr/local/lib/node_modules/learnyounode/learnyounode.js
 learnyounode@1.0.7 /usr/local/lib/node_modules/learnyounode
├── workshopper-boilerplate@0.0.1
├── duplexer@0.1.1
├── after@0.8.1
├── rimraf@2.2.8
├── boganipsum@0.1.0
├── through@2.3.6
├── hyperquest@0.2.0 (through@2.2.7)
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── colors-tmpl@0.1.1 (colors@0.6.2)
├── workshopper-wrappedexec@0.1.2 (xtend@2.1.2)
├── workshopper-exercise@0.2.3 (tuple-stream@0.0.2, split@0.3.2, xtend@2.1.2)
├── concat-stream@1.4.7 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
├── stream-browserify@1.0.0 (inherits@2.0.1, readable-stream@1.0.33)
├── bl@0.7.0 (readable-stream@1.0.33)
├── through2-map@1.4.0 (xtend@3.0.0, through2@0.5.1, terminus@1.0.11)
├── through2@0.4.2 (xtend@2.1.2, readable-stream@1.0.33)
└── workshopper@1.4.1 (map-async@0.1.1, xtend@3.0.0, mkdirp@0.3.5, visualwidth@0.0.1, optimist@0.6.1, terminal-menu@0.3.5, msee@0.1.1)
```

**Comment by cavpollo** [comment] 2015-01-15 20:42
Judging by the status code "http 304", it seems it is an entirely different problem =\

**Comment by martinheidegger** [comment] 2015-01-16 03:52
@cavpollo Your problems seems to be a general problem with [npm](https://github.com/npm/npm/issues) and not with learnyounode. Perhaps you can post an issue there?

@EverlessDrop41 Your seem to be working as intended with the problem that the registry had a missing abbrev module. probably fixed by now, can you retry?

**Comment by EverlessDrop41** [comment] 2015-01-16 17:16
@martinheidegger I tried installing it again, I get the same output and running `learnyounode` causes me to shift to a newline on my terminal. Should I create this as a separate issue?

**Closed** 2015-01-17 00:35 UTC
